# Generated by Django 3.0.5 on 2023-02-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230131_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='post',
            name='item',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='no_of_reports',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
