# Generated by Django 3.0.5 on 2023-02-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='city',
        ),
    ]
