# Generated by Django 3.0.5 on 2023-02-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
